### ISSUE TITLE
BUILD FAILURE：NoSuchKey

### ISSUE THREAD

**Issue by ishizak** [primecloud-controller-org/primecloud-controller-build#1]
会社Proxyが存在する環境で、primecloud-controller-buildを利用してビルドを行っています。
auto-uiのビルド時に下記のmavenメッセージが出力され、Failしてしまいます。
PCのブラウザで、メタデータが転送できない３ファイルのURLを直接指定すると
下記のメッセージが表示されました。
auto-uiのpom.xmlを修正する必要があると思います。対処方法を教えてください。
＝＝＝＝＝jackson-core-aslの場合＝＝＝＝＝

<pre>
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
vaadin-addons/org/codehaus/jackson/jackson-core-asl/maven-metadata.xml
</Key>
<RequestId>25932E13431EC1F0</RequestId>
<HostId>
V0R8wUVyBgd/IqI0DW1tiZqMkmeKWLLlsZnVYiqjgWEuXUkuwKP01qwVzxsnNOsq
</HostId>
</Error>
</pre>

＝＝＝＝＝jackson-core-aslの場合＝＝＝＝＝

＝＝＝＝＝Mavenのメッセージ（一部）＝＝＝＝＝
[INFO] Building auto-ui 2.4.0
[INFO] ------------------------------------------------------------------------
Downloading: http://maven.vaadin.com/vaadin-addons/commons-logging/commons-logging/maven-metadata.xml
[WARNING] Could not transfer metadata commons-logging:commons-logging/maven-metadata.xml from/to vaadin-addons (http://maven.vaadin.com/vaadin-addons): Connect to maven.vaadin.com:80 [maven.vaadin.com/54.86.23.48] failed: Connection timed out
Downloading: http://maven.vaadin.com/vaadin-addons/commons-httpclient/commons-httpclient/maven-metadata.xml
[WARNING] Could not transfer metadata commons-httpclient:commons-httpclient/maven-metadata.xml from/to vaadin-addons (http://maven.vaadin.com/vaadin-addons): Connect to maven.vaadin.com:80 [maven.vaadin.com/54.86.23.48] failed: Connection timed out
Downloading: http://maven.vaadin.com/vaadin-addons/org/codehaus/jackson/jackson-core-asl/maven-metadata.xml
[WARNING] Could not transfer metadata org.codehaus.jackson:jackson-core-asl/maven-metadata.xml from/to vaadin-addons (http://maven.vaadin.com/vaadin-addons): Connect to maven.vaadin.com:80 [maven.vaadin.com/54.86.23.48] failed: Connection timed out
＝＝＝＝＝Mavenのメッセージ（一部）＝＝＝＝＝

**Comment by aigamo** [comment]
確認しました。
これらの3ファイルはVaadinのアドオンではなく、MavenCentralから取得するべきものです。
何故かVaadin側のリポジトリを参照しているので、pom.xmlにMavenCentralを追記すると良いかと思います。

**Comment by aigamo** [comment]
https://gist.github.com/aigamo/eaddc2ac34cd73d5a404

Gistを参考に変更してみてください。

**Comment by aigamo** [comment]
変更内容をDevelopブランチに適用しておきました。

**Comment by ishizak** [comment]
ありがとうございました。
解決しました。
